version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./minio-storage:/data

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hackathone
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
#        condition:
#          service_started
#      minio
#        condition:
#          service_healthy

  proc:
    container_name: proc
    build:
      context: ./proc
    volumes:
      - ./proc/config.yaml:/usr/local/bin/config.yaml
    ports:
      - "8001"
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_USER: minio
      MINIO_PASSWORD: minio123
    restart: always
